AWSTemplateFormatVersion: "2010-09-09"
Description: "Reusable Google SecOps (Chronicle) Kinesis Firehose delivery stream for WAF Logs"

Parameters:

  Environment:
    Description: Deployment environment (dev, stage, qa, prod)
    Type: String
    AllowedValues:
      - dev
      - stage
      - qa
      - prod
    Default: stage

  FirewallName:
    Description: Short name of the firewall or policy set (e.g., waf, edge, corp-fw1)
    Type: String
    Default: waf

  FMSMonitoringBucketName:
    Description: Enter the bucket name for the WAF logs backup
    Type: String
    Default: fms-monitoring

  RegionPrefix:
    Description: Prefix of the region this is being deployed in
    Type: "AWS::SSM::Parameter::Value<String>"
    Default: /account_config/region_prefix
    AllowedValues:
      - /account_config/region_prefix

  FMSLogsRoleName:
    Description: Kinesis delivery role name (env-prefixed automatically)
    Type: String
    Default: "waf-firehose-delivery-role"

  LogTransformationFunctionName:
    Description: Lambda function used to transform WAF logs
    Type: String
    Default: "waf-logs-transformation"

  GoogleSecOpsHECToken:
    Description: Base secret name for Google SecOps token
    Type: String
    Default: "waf_google_secops_token"

  GoogleSecOpsTokenValue:
    Description: Google SecOps token (stored automatically into Secrets Manager)
    Type: String
    NoEcho: true

  GoogleSecOpsEndpoint:
    Description: Google SecOps (Chronicle) HTTP endpoint URL
    Type: String
    Default: "https://chronicle-forwarder.googleapis.com/v1/udmevents"

  GoogleSecOpsDeliveryStreamName:
    Description: Base name of the Google SecOps Kinesis Firehose stream
    Type: String
    Default: "aws-waf-logs-google-secops"


Resources:

  ###########################################################
  # Create a Secrets Manager Secret and store the token  #
  ###########################################################
  GoogleSecOpsTokenSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub "${Environment}-${GoogleSecOpsHECToken}"
      Description: !Sub "Google SecOps token for ${Environment} environment"
      SecretString: !Ref GoogleSecOpsTokenValue


  ###########################################################
  # 2. IAM Role for Firehose                                #
  ###########################################################
  DeliveryRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${RegionPrefix}-${Environment}-${FMSLogsRoleName}"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - firehose.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: firehose-s3-logs-and-secrets
          PolicyDocument:
            Version: "2012-10-17"
            Statement:

              - Effect: Allow
                Action:
                  - s3:AbortMultipartUpload
                  - s3:GetBucketLocation
                  - s3:GetObject
                  - s3:ListBucket
                  - s3:ListBucketMultipartUploads
                  - s3:PutObject
                  - s3:PutObjectAcl
                Resource:
                  - !Sub "arn:aws:s3:::${FMSMonitoringBucketName}"
                  - !Sub "arn:aws:s3:::${FMSMonitoringBucketName}/*"

              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/kinesisfirehose/${Environment}-${FirewallName}-${GoogleSecOpsDeliveryStreamName}:*"

              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                  - lambda:GetFunctionConfiguration
                Resource:
                  - !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${LogTransformationFunctionName}"

              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource:
                  - !Ref GoogleSecOpsTokenSecret


  ###########################################################
  # 3. Kinesis Firehose Delivery Stream                     #
  ###########################################################
  GoogleSecOpsDeliveryStream:
    Type: AWS::KinesisFirehose::DeliveryStream
    Properties:
      DeliveryStreamName: !Sub "${Environment}-${FirewallName}-${GoogleSecOpsDeliveryStreamName}"
      DeliveryStreamType: DirectPut

      HttpEndpointDestinationConfiguration:

        RoleARN: !GetAtt DeliveryRole.Arn

        EndpointConfiguration:
          Url: !Ref GoogleSecOpsEndpoint
          Name: "GoogleSecOps"

        BufferingHints:
          SizeInMBs: 5
          IntervalInSeconds: 60

        CloudWatchLoggingOptions:
          Enabled: true
          LogGroupName: !Sub "/aws/kinesisfirehose/${Environment}-${FirewallName}-${GoogleSecOpsDeliveryStreamName}"
          LogStreamName: "HttpEndpointDelivery"

        ProcessingConfiguration:
          Enabled: true
          Processors:
            - Type: Lambda
              Parameters:
                - ParameterName: LambdaArn
                  ParameterValue: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${LogTransformationFunctionName}"

        RequestConfiguration:
          ContentEncoding: "GZIP"

        RetryOptions:
          DurationInSeconds: 60

        S3BackupMode: FailedDataOnly
        S3Configuration:
          BucketARN: !Sub "arn:aws:s3:::${FMSMonitoringBucketName}"
          CompressionFormat: GZIP
          Prefix: !Sub "${Environment}/${FirewallName}/waf-logs/google-secops/failed/"
          RoleARN: !GetAtt DeliveryRole.Arn
          BufferingHints:
            SizeInMBs: 5
            IntervalInSeconds: 60
          CloudWatchLoggingOptions:
            Enabled: true
            LogGroupName: !Sub "/aws/kinesisfirehose/${Environment}-${FirewallName}-${GoogleSecOpsDeliveryStreamName}"
            LogStreamName: "S3Backup"

        SecretsManagerConfiguration:
          Enabled: true
          RoleARN: !GetAtt DeliveryRole.Arn
          SecretARN: !Ref GoogleSecOpsTokenSecret


Outputs:
  GoogleSecOpsFirehoseStreamName:
    Description: Name of the Google SecOps Firehose delivery stream
    Value: !Sub "${Environment}-${FirewallName}-${GoogleSecOpsDeliveryStreamName}"
