AWSTemplateFormatVersion: "2010-09-09"
Description: "Google SecOps (Chronicle) integration for AWS WAF Logs via S3 and SQS"

Parameters:

  Environment:
    Description: Deployment environment (dev, stage, qa, prod)
    Type: String
    AllowedValues:
      - dev
      - stage
      - qa
      - prod
    Default: stage

  FirewallName:
    Description: Short name of the firewall or policy set
    Type: String
    Default: waf

  FMSMonitoringBucketName:
    Description: S3 bucket name for WAF logs (must already exist)
    Type: String
    Default: "fms-monitoring"

  LogPrefix:
    Description: S3 prefix for WAF logs (optional, e.g., waf-logs/)
    Type: String
    Default: "waf-logs/"

  GoogleSecOpsSQSQueueName:
    Description: Name for the Google SecOps notification SQS queue
    Type: String
    Default: "google-secops-waf-logs-queue"

  MaxReceiveCount:
    Description: Maximum number of times a message can be received before being sent to DLQ
    Type: Number
    Default: 5
    MinValue: 1
    MaxValue: 1000


Resources:
  GoogleSecOpsDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "${Environment}-${FirewallName}-${GoogleSecOpsSQSQueueName}-dlq"
      MessageRetentionPeriod: 1209600
      ReceiveMessageWaitTimeSeconds: 20

  GoogleSecOpsSQSQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "${Environment}-${FirewallName}-${GoogleSecOpsSQSQueueName}"
      MessageRetentionPeriod: 1209600
      VisibilityTimeout: 300
      ReceiveMessageWaitTimeSeconds: 20
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt GoogleSecOpsDLQ.Arn
        maxReceiveCount: !Ref MaxReceiveCount


  GoogleSecOpsSQSQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref GoogleSecOpsSQSQueue
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowS3ToSendMessage
            Effect: Allow
            Principal:
              Service: s3.amazonaws.com
            Action:
              - sqs:SendMessage
            Resource: !GetAtt GoogleSecOpsSQSQueue.Arn
            Condition:
              ArnLike:
                aws:SourceArn: !Sub "arn:aws:s3:::${FMSMonitoringBucketName}"


Outputs:

  GoogleSecOpsSQSQueueURL:
    Description: URL of the Google SecOps SQS Queue
    Value: !Ref GoogleSecOpsSQSQueue

  GoogleSecOpsDLQURL:
    Description: URL of the DLQ
    Value: !Ref GoogleSecOpsDLQ
