AWSTemplateFormatVersion: "2010-09-09"
Description: "Creation of ONLY Google SecOps (Chronicle) Kinesis Firehose delivery stream for WAF Logs – JPro Stage Environment"

Parameters:
  FMSMonitoringBucketName:
    Description: Enter the bucket name for the WAF logs backup
    Type: String
    Default: fms-monitoring

  RegionPrefix:
    Description: Prefix of the region this is being deployed in
    Type: "AWS::SSM::Parameter::Value<String>"
    Default: /account_config/region_prefix
    AllowedValues:
      - /account_config/region_prefix

  FMSLogsRoleName:
    Description: Enter the name of waf logs Kinesis delivery role
    Type: String
    Default: "jpro-stage-waf-firehose-delivery-role"

  LogTransformationFunctionName:
    Description: Name of Lambda function used to transform WAF logs
    Type: String
    Default: "waf-logs-transformation"

  GoogleSecOpsHECToken:
    Description: Store Google SecOps HTTP endpoint token in Secrets Manager
    Type: String
    Default: jpro_stage_waf_google_secops_token

  GoogleSecOpsEndpoint:
    Description: Google SecOps (Chronicle) HTTP endpoint URL
    Type: String
    Default: "https://chronicle-forwarder.googleapis.com/v1/udmevents"

  GoogleSecOpsDeliveryStreamName:
    Description: Name for Google SecOps delivery stream
    Type: String
    Default: "aws-waf-logs-jpro-stage-google-secops"

Resources:
  DeliveryRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${RegionPrefix}-${FMSLogsRoleName}"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - firehose.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: firehose-s3-logs-and-secrets
          PolicyDocument:
            Version: "2012-10-17"
            Statement:

              # Allow writing to S3 backup bucket
              - Effect: Allow
                Action:
                  - s3:AbortMultipartUpload
                  - s3:GetBucketLocation
                  - s3:GetObject
                  - s3:ListBucket
                  - s3:ListBucketMultipartUploads
                  - s3:PutObject
                  - s3:PutObjectAcl
                Resource:
                  - !Sub "arn:aws:s3:::${FMSMonitoringBucketName}"
                  - !Sub "arn:aws:s3:::${FMSMonitoringBucketName}/*"

              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/kinesisfirehose/${GoogleSecOpsDeliveryStreamName}:*"

              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                  - lambda:GetFunctionConfiguration
                Resource:
                  - !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${LogTransformationFunctionName}"

              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource:
                  - !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${GoogleSecOpsHECToken}*"

  GoogleSecOpsDeliveryStream:
    Type: AWS::KinesisFirehose::DeliveryStream
    Properties:
      DeliveryStreamName: !Ref GoogleSecOpsDeliveryStreamName
      DeliveryStreamType: DirectPut
      
      HttpEndpointDestinationConfiguration:

        EndpointConfiguration:
          Url: !Ref GoogleSecOpsEndpoint
          Name: "GoogleSecOps"

        BufferingHints:
          SizeInMBs: 5
          IntervalInSeconds: 60

        CloudWatchLoggingOptions:
          Enabled: true
          LogGroupName: !Sub "/aws/kinesisfirehose/${GoogleSecOpsDeliveryStreamName}"
          LogStreamName: "HttpEndpointDelivery"

        ProcessingConfiguration:
          Enabled: true
          Processors:
            - Type: Lambda
              Parameters:
                - ParameterName: LambdaArn
                  ParameterValue: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${LogTransformationFunctionName}"

        RequestConfiguration:
          ContentEncoding: "GZIP"

        RetryOptions:
          DurationInSeconds: 60

        S3BackupMode: FailedDataOnly
        S3Configuration:
          BucketARN: !Sub "arn:aws:s3:::${FMSMonitoringBucketName}"
          CompressionFormat: GZIP
          Prefix: "waf-logs/google-secops/failed/"
          RoleARN: !GetAtt DeliveryRole.Arn
          BufferingHints:
            SizeInMBs: 5
            IntervalInSeconds: 60
          CloudWatchLoggingOptions:
            Enabled: true
            LogGroupName: !Sub "/aws/kinesisfirehose/${GoogleSecOpsDeliveryStreamName}"
            LogStreamName: "S3Backup"

        SecretsManagerConfiguration:
          Enabled: true
          RoleARN: !GetAtt DeliveryRole.Arn
          SecretARN: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${GoogleSecOpsHECToken}"

Outputs:
  GoogleSecOpsFirehoseStreamName:
    Description: Name of the Google SecOps Firehose delivery stream
    Value: !Ref GoogleSecOpsDeliveryStream
