AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  CloudWatch Logs processor Lambda that forwards logs
  from /aws/lambda/jamf-now-to-splunk
  directly to Google SecOps (Chronicle) via webhook.

Resources:

  LogsProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: waf-ip-manage-secops-cloudwatch-logs-processor
      Runtime: python3.11
      Handler: index.lambda_handler
      Timeout: 30
      CodeUri: .
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
                - secretsmanager:DescribeSecret
              Resource: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:waf-ip-manage-secops-creds*


  LogsProcessorPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt LogsProcessorFunction.Arn
      Action: lambda:InvokeFunction
      Principal: !Sub logs.${AWS::Region}.amazonaws.com
      SourceArn: !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/jamf-now-to-splunk:*

  JamfNowToSplunkSubscriptionFilter:
    Type: AWS::Logs::SubscriptionFilter
    DependsOn: LogsProcessorPermission
    Properties:
      LogGroupName: /aws/lambda/jamf-now-to-splunk
      FilterPattern: ""
      DestinationArn: !GetAtt LogsProcessorFunction.Arn
