AWSTemplateFormatVersion: '2010-09-09'
Description: Chronicle CloudTrail ingestion with KMS, EventBridge -> SNS -> SQS

Parameters:
  CloudTrailBucketName:
    Type: String
    Description: Existing CloudTrail S3 bucket name

Resources:
  ChronicleKMSKey:
    Type: AWS::KMS::Key
    Properties:
      Description: KMS key for SNS and SQS encryption (scoped access)
      EnableKeyRotation: true
      KeyPolicy:
        Version: '2012-10-17'
        Statement:
          - Sid: RootAccess
            Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
            Action: kms:*
            Resource: '*'

          - Sid: AllowSNSTopicUse
            Effect: Allow
            Principal:
              Service: sns.amazonaws.com
            Action:
              - kms:Decrypt
              - kms:GenerateDataKey
            Resource: '*'
            Condition:
              StringEquals:
                aws:SourceArn: !Ref CloudTrailSNSTopic
                aws:SourceAccount: !Ref AWS::AccountId

          - Sid: AllowSQSUse
            Effect: Allow
            Principal:
              Service: sqs.amazonaws.com
            Action:
              - kms:Decrypt
              - kms:GenerateDataKey
            Resource: '*'
            Condition:
              StringEquals:
                aws:SourceArn: !GetAtt CloudTrailSQSQueue.Arn
                aws:SourceAccount: !Ref AWS::AccountId

  ChronicleKMSAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: alias/chronicle-cloudtrail-key
      TargetKeyId: !Ref ChronicleKMSKey

  CloudTrailSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: CloudTrail-Notification-Topic
      KmsMasterKeyId: !Ref ChronicleKMSKey

  SNSTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - !Ref CloudTrailSNSTopic
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowEventBridgePublish
            Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sns:Publish
            Resource: !Ref CloudTrailSNSTopic

  CloudTrailSQSQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: CloudTrail-Notification-Queue
      KmsMasterKeyId: !Ref ChronicleKMSKey
      KmsDataKeyReusePeriodSeconds: 300

  SQSQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref CloudTrailSQSQueue
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowSNSPublish
            Effect: Allow
            Principal:
              Service: sns.amazonaws.com
            Action: SQS:SendMessage
            Resource: !GetAtt CloudTrailSQSQueue.Arn
            Condition:
              ArnEquals:
                aws:SourceArn: !Ref CloudTrailSNSTopic

  SNSSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref CloudTrailSNSTopic
      Protocol: sqs
      Endpoint: !GetAtt CloudTrailSQSQueue.Arn
      RawMessageDelivery: true

  PutObjectEventRule:
    Type: AWS::Events::Rule
    Properties:
      Name: CloudTrail-S3-PutObject-Notify
      EventPattern:
        source:
          - aws.s3
        detail-type:
          - AWS API Call via CloudTrail
        detail:
          eventName:
            - PutObject
          requestParameters:
            bucketName:
              - !Ref CloudTrailBucketName
      Targets:
        - Arn: !Ref CloudTrailSNSTopic
          Id: SendToSNS

Outputs:
  KMSKeyArn:
    Value: !GetAtt ChronicleKMSKey.Arn

  SNSTopicArn:
    Value: !Ref CloudTrailSNSTopic

  SQSQueueArn:
    Value: !GetAtt CloudTrailSQSQueue.Arn

  SQSQueueURL:
    Value: !Ref CloudTrailSQSQueue
