AWSTemplateFormatVersion: '2010-09-09'
Description: Chronicle CloudTrail ingestion with EventBridge -> SNS -> SQS

Parameters:
  CloudTrailBucketName:
    Type: String
    Default: google-feed-secops-bucket
    Description: Existing CloudTrail S3 bucket name

Resources:

  CloudTrailSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: CloudTrail-Notification-Topic

  SNSTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - !Ref CloudTrailSNSTopic
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowEventBridgePublish
            Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action:
              - sns:Publish
            Resource: !Ref CloudTrailSNSTopic

  CloudTrailSQSQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: CloudTrail-Notification-Queue
      VisibilityTimeout: 30 # optional
      MessageRetentionPeriod: 345600 # optional (4 days)

  SQSQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref CloudTrailSQSQueue
      PolicyDocument:
        Version: '2012-10-17'
        Id: __default_policy_ID
        Statement:
          - Sid: __owner_statement
            Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
            Action:
              - SQS:*
            Resource: !GetAtt CloudTrailSQSQueue.Arn

          - Sid: AllowSNSPublish
            Effect: Allow
            Principal:
              Service: sns.amazonaws.com
            Action:
              - SQS:SendMessage
            Resource: !GetAtt CloudTrailSQSQueue.Arn
            Condition:
              ArnEquals:
                aws:SourceArn: !Ref CloudTrailSNSTopic

  SNSSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref CloudTrailSNSTopic
      Protocol: sqs
      Endpoint: !GetAtt CloudTrailSQSQueue.Arn
      RawMessageDelivery: true

  PutObjectEventRule:
    Type: AWS::Events::Rule
    Properties:
      Name: CloudTrail-S3-PutObject-Notify
      EventPattern:
        source:
          - aws.s3
        detail-type:
          - AWS API Call via CloudTrail
        detail:
          eventName:
            - PutObject
          requestParameters:
            bucketName:
              - !Ref CloudTrailBucketName
      Targets:
        - Arn: !Ref CloudTrailSNSTopic
          Id: SendToSNS

Outputs:
  SNSTopicArn:
    Value: !Ref CloudTrailSNSTopic

  SQSQueueArn:
    Value: !GetAtt CloudTrailSQSQueue.Arn

  SQSQueueURL:
    Value: !Ref CloudTrailSQSQueue
