AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: CloudTrail S3 → Lambda → SQS Routing

Parameters:

  S3BucketName:
    Type: String
    Default: jamf-global-cloudtrail-logs

  USCompliantAccounts:
    Type: String
    Default: "315987135019,453013692738,444490906999,221212361977,400235226088,279250952523,384261514181,426741698857,612294365027,642848149852,266023621710,142217395313,556396476912,667623697424,723066671449,588009609257,603843106361,081700944673,102055880387,734913321718,799006065355,953770353853,857960491540,802681188238,748506105067,637423430067,891376983106,654654495066,851725276293"

  RegionName:
    Type: String
    Default: us-east-1

  EventNameExcludedList:
    Type: String
    Default: "AssumeRole,GetCallerIdentity"

  EventRoleArnExcludedList:
    Type: String
    Default: ""

Resources:

  LambdaDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: jamf-secops-dlq
      SqsManagedSseEnabled: true

  USCompliantQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: jamf-us-compliant-queue
      VisibilityTimeout: 300
      MessageRetentionPeriod: 345600
      SqsManagedSseEnabled: true
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt LambdaDLQ.Arn
        maxReceiveCount: 5

  NonUSCompliantQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: jamf-us-non-compliant-queue
      VisibilityTimeout: 300
      MessageRetentionPeriod: 345600
      SqsManagedSseEnabled: true
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt LambdaDLQ.Arn
        maxReceiveCount: 5

  NonUSQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref NonUSCompliantQueue
      PolicyDocument:
        Version: "2012-10-17"
        Statement:

          - Sid: OwnerFullAccess
            Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
            Action: "SQS:*"
            Resource: !GetAtt NonUSCompliantQueue.Arn

          - Sid: AllowLambdaToSendMessage
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: SQS:SendMessage
            Resource: !GetAtt NonUSCompliantQueue.Arn

  USQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref USCompliantQueue
      PolicyDocument:
        Version: "2012-10-17"
        Statement:

          - Sid: OwnerFullAccess
            Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
            Action: "SQS:*"
            Resource: !GetAtt USCompliantQueue.Arn

          - Sid: AllowLambdaToSendMessage
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: SQS:SendMessage
            Resource: !GetAtt USCompliantQueue.Arn

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: jamf-secops-lambda-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole

      Policies:
        - PolicyName: lambda-policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:

              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"

              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource: !Sub arn:aws:s3:::${S3BucketName}/*

              - Effect: Allow
                Action:
                  - sqs:SendMessage
                  - sqs:SendMessageBatch
                Resource:
                  - !GetAtt USCompliantQueue.Arn
                  - !GetAtt NonUSCompliantQueue.Arn
                  - !GetAtt LambdaDLQ.Arn

  CloudTrailProcessorLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: jamf-secops-lambda
      Runtime: python3.14
      Handler: index.lambda_handler
      CodeUri: .
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 300
      MemorySize: 512

      Environment:
        Variables:
          EVENT_NAME_EXCLUDED_LIST: !Ref EventNameExcludedList
          EVENT_ROLE_ARN_EXCLUDED_LIST: !Ref EventRoleArnExcludedList
          US_COMPLIANT_ACCOUNTS: !Ref USCompliantAccounts
          REGION_NAME: !Ref RegionName
          US_COMPLIANT_QUEUE_URL: !Ref USCompliantQueue
          NON_US_COMPLIANT_QUEUE_URL: !Ref NonUSCompliantQueue

      DeadLetterQueue:
        Type: SQS
        TargetArn: !GetAtt LambdaDLQ.Arn

  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref CloudTrailProcessorLambda
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceArn: !Sub arn:aws:s3:::${S3BucketName}

Outputs:

  LambdaName:
    Value: !Ref CloudTrailProcessorLambda

  USQueueURL:
    Value: !Ref USCompliantQueue

  NonUSQueueURL:
    Value: !Ref NonUSCompliantQueue
