AWSTemplateFormatVersion: '2010-09-09'
Description: |
  Google SecOps CloudTrail Integration. EventBridge rule -> SNS topic -> SQS Standard queue. Assumes existing S3 bucket, CloudTrail trail, and IAM user.

Parameters:
  ExistingS3BucketName:
    Type: String
    Description: Name of your existing S3 bucket where CloudTrail logs are stored.

Resources:
  SecOpsKMSKey:
    Type: AWS::KMS::Key
    Properties:
      Description: KMS key for Google SecOps SNS and SQS encryption.
      Enabled: true
      EnableKeyRotation: true
      KeyPolicy:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowRootFullAccess
            Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
            Action: kms:*
            Resource: '*'
          - Sid: AllowEventBridge
            Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action:
              - kms:GenerateDataKey
              - kms:Decrypt
            Resource: '*'
          - Sid: AllowSNS
            Effect: Allow
            Principal:
              Service: sns.amazonaws.com
            Action:
              - kms:GenerateDataKey
              - kms:Decrypt
            Resource: '*'

  SecOpsKMSKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: alias/secops-sns-sqs-key
      TargetKeyId: !Ref SecOpsKMSKey

  CloudTrailNotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: CloudTrail-Notification-Topic
      KmsMasterKeyId: !Ref SecOpsKMSKey

  CloudTrailNotificationTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - !Ref CloudTrailNotificationTopic
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowEventBridgePublish
            Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sns:Publish
            Resource: !Ref CloudTrailNotificationTopic

  CloudTrailNotificationQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: CloudTrail-Notification-Queue
      KmsMasterKeyId: !Ref SecOpsKMSKey
      KmsDataKeyReusePeriodSeconds: 300
      VisibilityTimeout: 300
      MessageRetentionPeriod: 1209600

  CloudTrailNotificationQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref CloudTrailNotificationQueue
      PolicyDocument:
        Version: '2012-10-17'
        Id: PolicyForSNS
        Statement:
          - Sid: AllowSNS
            Effect: Allow
            Principal:
              Service: sns.amazonaws.com
            Action: sqs:SendMessage
            Resource: !GetAtt CloudTrailNotificationQueue.Arn
            Condition:
              ArnEquals:
                aws:SourceArn: !Ref CloudTrailNotificationTopic

  SNSToSQSSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref CloudTrailNotificationTopic
      Protocol: sqs
      Endpoint: !GetAtt CloudTrailNotificationQueue.Arn
      RawMessageDelivery: true

  CloudTrailPutObjectRule:
    Type: AWS::Events::Rule
    Properties:
      Name: cloudtrail-s3-putobject-secops
      Description: Detects PutObject on CloudTrail S3 bucket, forwards to SNS.
      State: ENABLED
      EventPattern:
        source:
          - aws.s3
        detail-type:
          - AWS API Call via CloudTrail
        detail:
          eventName:
            - PutObject
          requestParameters:
            bucketName:
              - !Ref ExistingS3BucketName
      Targets:
        - Id: CloudTrailSNSTarget
          Arn: !Ref CloudTrailNotificationTopic

Outputs:
  KMSKeyArn:
    Description: KMS Key ARN used for SNS and SQS encryption.
    Value: !GetAtt SecOpsKMSKey.Arn

  KMSKeyAlias:
    Description: KMS Key alias.
    Value: alias/secops-sns-sqs-key

  SNSTopicArn:
    Description: SNS Topic ARN.
    Value: !Ref CloudTrailNotificationTopic

  SQSQueueURL:
    Description: SQS Queue URL for Google SecOps feed configuration.
    Value: !Ref CloudTrailNotificationQueue

  SQSQueueArn:
    Description: SQS Queue ARN.
    Value: !GetAtt CloudTrailNotificationQueue.Arn
