AWSTemplateFormatVersion: '2010-09-09'
Description: StateRAMP / FedRAMP Firehose to send CloudTrail logs to Google SecOps

Parameters:
  GoogleSecOpsEndpointUrl:
    Type: String
    Description: Google SecOps endpoint URL
    NoEcho: true
  GoogleSecOpsApiKey:
    Type: String
    Description: Google SecOps API key
    NoEcho: true
  GoogleSecOpsAccessKey:
    Type: String
    Description: Google SecOps access token
    NoEcho: true
  FirehoseStreamName:
    Type: String
    Default: Google-SecOps-Cloudtrail-StateRAMP-Put
    Description: StateRAMP / FedRAMP Firehose delivery stream name
  BackupBucketName:
    Type: String
    Default: 756875170482-google-secops-cloudtrail
    Description: S3 bucket for Firehose backup / failed delivery

Resources:
  FirehoseLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/kinesisfirehose/${FirehoseStreamName}
      RetentionInDays: 30

  FirehoseLogStreamHttp:
    Type: AWS::Logs::LogStream
    Properties:
      LogGroupName: !Ref FirehoseLogGroup
      LogStreamName: HttpEndpointDelivery

  FirehoseLogStreamS3:
    Type: AWS::Logs::LogStream
    Properties:
      LogGroupName: !Ref FirehoseLogGroup
      LogStreamName: S3BackupDelivery

  FirehoseDeliveryRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: cloudtrail-to-google-secops-firehose-stateramp-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: firehose.amazonaws.com
            Action: sts:AssumeRole

  FirehoseDeliveryPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: cloudtrail-to-google-secops-firehose-stateramp-policy
      Roles:
        - !Ref FirehoseDeliveryRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - s3:AbortMultipartUpload
              - s3:GetBucketLocation
              - s3:GetObject
              - s3:ListBucket
              - s3:ListBucketMultipartUploads
              - s3:PutObject
            Resource:
              - !Sub arn:aws:s3:::${BackupBucketName}
              - !Sub arn:aws:s3:::${BackupBucketName}/*
          - Effect: Allow
            Action:
              - logs:PutLogEvents
              - logs:CreateLogStream
            Resource:
              - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/kinesisfirehose/${FirehoseStreamName}:*

  CloudTrailStateRAMPFirehose:
    Type: AWS::KinesisFirehose::DeliveryStream
    DependsOn:
      - FirehoseDeliveryPolicy
      - FirehoseLogStreamHttp
      - FirehoseLogStreamS3
    Properties:
      DeliveryStreamName: !Ref FirehoseStreamName
      DeliveryStreamType: DirectPut
      HttpEndpointDestinationConfiguration:
        RoleARN: !GetAtt FirehoseDeliveryRole.Arn
        EndpointConfiguration:
          Name: google-secops-uscompliant
          Url: !Sub '${GoogleSecOpsEndpointUrl}?key=${GoogleSecOpsApiKey}'
          AccessKey: !Ref GoogleSecOpsAccessKey
        BufferingHints:
          IntervalInSeconds: 300
          SizeInMBs: 64
        RetryOptions:
          DurationInSeconds: 300
        CloudWatchLoggingOptions:
          Enabled: true
          LogGroupName: !Ref FirehoseLogGroup
          LogStreamName: HttpEndpointDelivery
        S3BackupMode: FailedDataOnly
        S3Configuration:
          RoleARN: !GetAtt FirehoseDeliveryRole.Arn
          BucketARN: !Sub arn:aws:s3:::${BackupBucketName}
          CompressionFormat: GZIP
          CloudWatchLoggingOptions:
            Enabled: true
            LogGroupName: !Ref FirehoseLogGroup
            LogStreamName: S3BackupDelivery

Outputs:
  FirehoseName:
    Description: StateRAMP / FedRAMP Firehose Stream Name
    Value: !Ref CloudTrailStateRAMPFirehose
  FirehoseLogGroup:
    Description: CloudWatch Log Group for Firehose errors
    Value: !Ref FirehoseLogGroup
