AWSTemplateFormatVersion: '2010-09-09'
Description: StateRAMP / FedRAMP Firehose to send CloudTrail logs to Google SecOps

Parameters:
  GoogleSecOpsEndpointUrl:
    Type: String
    Description: Google SecOps endpoint URL (e.g., https://malachiteingestion-pa.googleapis.com/v2/unstructuredlogentries:batchCreate)
    NoEcho: true
  GoogleSecOpsApiKey:
    Type: String
    Description: Google SecOps API key
    NoEcho: true
  GoogleSecOpsAccessKey:
    Type: String
    Description: Google SecOps access token
    NoEcho: true
  FirehoseStreamName:
    Type: String
    Default: aws-cloudtrail-uscompliant-logs-to-google-secops
    Description: StateRAMP / FedRAMP Firehose delivery stream name
  BackupBucketName:
    Type: String
    Default: 756875170482-google-secops-cloudtrail
    Description: S3 bucket for Firehose backup / failed delivery

Resources:
  FirehoseDeliveryRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: cloudtrail-to-google-secops-firehose-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: firehose.amazonaws.com
            Action: sts:AssumeRole

  FirehoseDeliveryPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: cloudtrail-to-google-secops-firehose-policy
      Roles:
        - !Ref FirehoseDeliveryRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - s3:AbortMultipartUpload
              - s3:GetBucketLocation
              - s3:GetObject
              - s3:ListBucket
              - s3:ListBucketMultipartUploads
              - s3:PutObject
            Resource:
              - !Sub arn:aws:s3:::${BackupBucketName}
              - !Sub arn:aws:s3:::${BackupBucketName}/*
          - Effect: Allow
            Action:
              - logs:PutLogEvents
            Resource:
              - !Sub arn:aws:logs:*:${AWS::AccountId}:log-group:/aws/kinesisfirehose/${FirehoseStreamName}:*

  CloudTrailStateRAMPFirehose:
    Type: AWS::KinesisFirehose::DeliveryStream
    DependsOn: FirehoseDeliveryPolicy
    Properties:
      DeliveryStreamName: !Ref FirehoseStreamName
      DeliveryStreamType: DirectPut
      HttpEndpointDestinationConfiguration:
        RoleARN: !GetAtt FirehoseDeliveryRole.Arn
        EndpointConfiguration:
          Name: google-secops-uscompliant
          Url: !Sub '${GoogleSecOpsEndpointUrl}?key=${GoogleSecOpsApiKey}'
          AccessKey: !Ref GoogleSecOpsAccessKey
        BufferingHints:
          IntervalInSeconds: 300
          SizeInMBs: 64
        RetryOptions:
          DurationInSeconds: 300
        S3BackupMode: FailedDataOnly
        S3Configuration:
          RoleARN: !GetAtt FirehoseDeliveryRole.Arn
          BucketARN: !Sub arn:aws:s3:::${BackupBucketName}
          CompressionFormat: GZIP

Outputs:
  FirehoseName:
    Description: StateRAMP / FedRAMP Firehose Stream Name
    Value: !Ref CloudTrailStateRAMPFirehose
