AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Firehose Delivery Stream to ingest CloudTrail logs to Google SecOps
  with Lambda-based filtering

Parameters:
  GoogleSecOpsSecretName:
    Type: String
    Default: google-secops-credentials

  GoogleSecOpsEndpointUrl:
    Type: String
    Default: Secops-endpoint_url

  GoogleSecOpsApiKey:
    Type: String
    Default: Secops-api_key

  EventRole:
    Type: String
    Default: ExportTaskRole,ExtractRole,Extract-10J5Z8O7JDV9A,EmrFS-Session,Extract-JUKG0T0AARWX,XProtectMRTDynamoDBTableReadOnlyRole,spinnakerManaged-terraform,newrelic-infrastructure

  EventName:
    Type: String
    Default: Decrypt,GenerateDataKey,AssumeRole,GetBucketLocation,Encrypt

  StreamName:
    Type: String
    Default: aws-cloudtrail-logs-to-google-secops

  BucketName:
    Type: String
    Default: jamf-global-cloudtrail-logs

  RegionName:
    Type: String
    Default: us-east-1

Resources:

  FirehoseLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/kinesisfirehose/${StreamName}
      RetentionInDays: 14

  FirehoseLogStream:
    Type: AWS::Logs::LogStream
    Properties:
      LogGroupName: !Ref FirehoseLogGroup
      LogStreamName: HttpEndpointDelivery

  DeliveryRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: cloudtrail-to-google-secops-delivery-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: firehose.amazonaws.com
            Action: sts:AssumeRole

  DeliveryPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: cloudtrail-to-google-secops-firehose-policy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - s3:AbortMultipartUpload
              - s3:GetBucketLocation
              - s3:GetObject
              - s3:ListBucket
              - s3:ListBucketMultipartUploads
              - s3:PutObject
            Resource:
              - !Sub arn:aws:s3:::${BucketName}
              - !Sub arn:aws:s3:::${BucketName}/*

          - Effect: Allow
            Action:
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource:
              - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/kinesisfirehose/${StreamName}:*

      Roles:
        - !Ref DeliveryRole

  CloudtrailDeliveryStream:
    Type: AWS::KinesisFirehose::DeliveryStream
    Properties:
      DeliveryStreamName: !Ref StreamName
      DeliveryStreamType: DirectPut

      HttpEndpointDestinationConfiguration:
        EndpointConfiguration:
          Name: google-secops
          Url: !Sub '{{resolve:secretsmanager:${GoogleSecOpsSecretName}:SecretString:${GoogleSecOpsEndpointUrl}}}?key={{resolve:secretsmanager:${GoogleSecOpsSecretName}:SecretString:${GoogleSecOpsApiKey}}}'
        BufferingHints:
          IntervalInSeconds: 300
          SizeInMBs: 64

        RetryOptions:
          DurationInSeconds: 300

        CloudWatchLoggingOptions:
          Enabled: true
          LogGroupName: !Ref FirehoseLogGroup
          LogStreamName: !Ref FirehoseLogStream

        S3Configuration:
          BucketARN: !Sub arn:aws:s3:::${BucketName}
          RoleARN: !GetAtt DeliveryRole.Arn
          CompressionFormat: GZIP

  CloudtrailLogsFilteringFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole

      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

      Policies:
        - PolicyName: CloudtrailLogsFilteringInlinePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - firehose:PutRecordBatch
                Resource:
                  - !GetAtt CloudtrailDeliveryStream.Arn

  CloudtrailLogsFilteringFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: cloudtrail-logs-filtering
      Runtime: python3.12
      Handler: cloudtrail-logs-filtering.lambda_handler
      CodeUri: .
      MemorySize: 256
      Timeout: 500
      Role: !GetAtt CloudtrailLogsFilteringFunctionRole.Arn
      Environment:
        Variables:
          STREAM_NAME: !Ref StreamName
          EVENT_NAME_EXCLUDED_LIST: !Ref EventName
          EVENT_ROLE_ARN_EXCLUDED_LIST: !Ref EventRole

